-- Script para criar tabelas de produtos, cores, tamanhos e grades

-- Remover tabelas se existirem (para um reset completo do esquema)
DROP TABLE IF EXISTS public.produto_grades CASCADE;
DROP TABLE IF EXISTS public.produtos CASCADE;
DROP TABLE IF EXISTS public.cores CASCADE;
DROP TABLE IF EXISTS public.tamanhos CASCADE;

-- Tabela de Produtos
CREATE TABLE public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao TEXT,
    categoria TEXT,
    genero TEXT,
    faixa_etaria TEXT,
    tipo_manga TEXT,
    unidade_medida TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Cores
CREATE TABLE public.cores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    hex_code TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Tamanhos
CREATE TABLE public.tamanhos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    ordem INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Grades de Produtos
CREATE TABLE public.produto_grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
    cor_id BIGINT REFERENCES public.cores(id) ON DELETE SET NULL,
    tamanho_id BIGINT REFERENCES public.tamanhos(id) ON DELETE SET NULL,
    sku TEXT UNIQUE,
    custo_centavos INT,
    preco_venda_centavos INT,
    estoque INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para otimização de consultas
CREATE INDEX idx_produto_grades_produto_id ON public.produto_grades(produto_id);
CREATE INDEX idx_produto_grades_cor_id ON public.produto_grades(cor_id);
CREATE INDEX idx_produto_grades_tamanho_id ON public.produto_grades(tamanho_id);
CREATE INDEX idx_produto_grades_sku ON public.produto_grades(sku);
